--- #YAML:1.0
name: Kephra
version: 0.3.4.3
abstract: crossplatform GUI Text-Editor
author: lichtkind@cpan.org
license: gpl
distribution_type: module
generated_by: Module::Install version 1.00
no_index: 
  directory: 
    - doc
    - inc
    - lib/Kephra
    - share
    - t
    - xt
requires: 
  perl: 5.006
  Cwd: 0
  POSIX: 0
  Text-Wrap: 0
  Encode-Guess: 0
  File-Find: 0
  File-UserConfig: 0
  Config-General: 0.30
  YAML-Tiny: 0.31
  Wx:   0.91
  Wx-Perl-ProcessStream: 0
resources:
  homepage: http://kephra.sf.net
  repository: http://kephra.svn.sourceforge.net/viewvc/kephra/dev/base/
  mailinglist: http://lists.sourceforge.net/lists/listinfo/kephra-tester
  license: http://www.gnu.org/licenses/gpl-2.0.html
