--- #YAML:1.0
name: Kephra
version: 0.3.10.5
abstract: crossplatform GUI Text-Editor
author: lichtkind@cpan.org
license: gpl
distribution_type: module
generated_by: Module::Install version 0.68
no_index: 
  directory: 
    - doc
    - inc
    - share
    - t
    - xt
requires: 
  perl: 5.006
  Wx:   0.70
  Wx-Perl-ProcessStream: 0
  YAML-Tiny: 0.31
  Config-General: 0.30
  Cwd: 0
  File-Find: 0
  File-UserConfig: 0
  Text-Wrap: 0
resources:
    homepage: http://kephra.sf.net
    repository: http://kephra.svn.sourceforge.net/viewvc/kephra/dev/base/
    MailingList: http://lists.sourceforge.net/lists/listinfo/kephra-tester
