---
abstract: 'crossplatform, GUI-Texteditor along Perl alike Paradigms '
author:
  - 'Herbert Breunung'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.47
  Test::NoWarnings: 0
  Test::Script: 0.01
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kephra
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Config::General: 2.4
  Cwd: 0
  Encode::Guess: 0
  File::UserConfig: 0
  POSIX: 0
  Text::Wrap: 0
  Wx: 0.94
  Wx::Perl::ProcessStream: 0.25
  YAML::Tiny: 0.31
  perl: 5.6.0
resources:
  bugtracker: http://sourceforge.net/tracker/?group_id=169747&atid=851590
  homepage: http://kephra.sourceforge.net/
  license: http://opensource.org/licenses/gpl-license.php
version: 0.4.3.21
