---
document:
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 11933
    edit_pos: 7722
    file_path: '/home/lichtkind/txt/artikel/freiesmagazin/perlintro.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: auto
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 59
    edit_pos: 74
    file_path: '/home/lichtkind/txt/artikel/$foo/perl6_up5.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: auto
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 12887
    edit_pos: 2605
    file_path: '/home/lichtkind/txt/artikel/freiesmagazin/perlinto.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 0
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 59
    edit_pos: 59
    file_path: '/home/lichtkind/txt/artikel/$foo/perl6_up4.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: auto
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 134
    edit_pos: 134
    file_path: '/home/lichtkind/code/perl/project/editor/dev/base/lib/Kephra/App.pm'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 0
    edit_pos: 3587
    file_path: '/home/lichtkind/code/perl/project/trigon/src/Trigon.pm'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 15044
    edit_pos: 15044
    file_path: '/home/lichtkind/code/perl/project/trigon/src/wxtrigon.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 65
    edit_pos: 64
    file_path: '/home/lichtkind/code/perl/project/trigon/src/test.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: auto
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 3829
    edit_pos: 4854
    file_path: '/home/lichtkind/code/perl/project/graphik/harmonograph/harmonograph.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 0
    edit_pos: '-1'
    file_path: '/home/lichtkind/code/perl/project/trigon/eigene/worte.yml'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: yaml
    tab_size: 4
    tab_use: 0
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 0
    edit_pos: 12167
    file_path: '/home/lichtkind/code/perl/project/graphik/harmonograph/share/Harmonograph.xrc'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: xml
    tab_size: 4
    tab_use: 1
  -
    EOL: lf
    codepage: utf8
    config_file: ~
    cursor_pos: 1604
    edit_pos: 574
    file_path: '/home/lichtkind/code/perl/project/graphik/harmonograph/harmonographxrc.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 0
    edit_pos: '-1'
    file_path: '/home/lichtkind/txt/artikel/heise/perl5.14release.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 1
